name: PR 5-Min Fail Job for 'fail' Commits

on:
  pull_request:
    branches:
      - main  # or your default target branch
    types: [opened, synchronize, reopened]

jobs:
  run-if-commit-has-fail:
    if: contains(github.event.pull_request.head.commit.message, 'fail')
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Fail on purpose
        run: |
          echo "❌ Failing the job after 5 minutes due to commit: '${{ github.event.pull_request.head.commit.message }}'"
          exit 1
